Ecommerce.WebUI/ViewComponents/AdminDetailViewComponent.cs
using Ecommerce.Entity;
using Ecommerce.WebUI.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.WebUI.ViewComponents
{
    public class AdminDetailViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(){
            User user = HttpContext.Session.GetObject<User>("admin");


            return View(user);
        }
    }
}

Ecommerce.WebUI/Views/Admin/AddCategory.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@model Category

<div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                            <li class="breadcrumb-item active">Category Add</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Add Category</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <form asp-controller="Admin" asp-action="SaveCategory" method="POST">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card-box">

                                    <div class="form-group mb-3">
                                        <label asp-for="Name"></label> <span class="text-danger">*</span>
                                        <input asp-for="Name" class="form-control" placeholder="Category Name">
                                    </div>                                    
                                </div> <!-- end card-box -->
                            </div> <!-- end col -->


                        </div>
                        <!-- end row -->

                        <div class="row">
                            <div class="col-12">
                                <div class="text-center mb-3">
                                    <button type="submit" class="btn w-sm btn-success waves-effect waves-light">Save</button>
                                </div>
                            </div> <!-- end col -->
                        </div>

                        </form>
                        <!-- end row -->


                        <!-- file preview template -->
                        <div class="d-none" id="uploadPreviewTemplate">
                            <div class="card mt-1 mb-0 shadow-none border">
                                <div class="p-2">
                                    <div class="row align-items-center">
                                        <div class="col-auto">
                                            <img data-dz-thumbnail="" src="#" class="avatar-sm rounded bg-light" alt="">
                                        </div>
                                        <div class="col pl-0">
                                            <a href="javascript:void(0);" class="text-muted font-weight-bold" data-dz-name=""></a>
                                            <p class="mb-0" data-dz-size=""></p>
                                        </div>
                                        <div class="col-auto">
                                            <!-- Button -->
                                            <a href="" class="btn btn-link btn-lg text-muted" data-dz-remove="">
                                                <i class="dripicons-cross"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        
                    </div> <!-- container -->

                </div>


@section Scripts{

        <!-- Summernote js -->
        <script src="/assets/libs/summernote/summernote-bs4.min.js"></script>
        <!-- Select2 js-->
        <script src="/assets/libs/select2/js/select2.min.js"></script>
        <!-- Dropzone file uploads-->
        <script src="/assets/libs/dropzone/min/dropzone.min.js"></script>

        <!-- Init js-->
        <script src="/assets/js/pages/form-fileuploads.init.js"></script>

        <!-- Init js -->
        <script src="/assets/js/pages/add-product.init.js"></script>

}

@section Styles{
        <link href="/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/summernote/summernote-bs4.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/dropzone/min/dropzone.min.css" rel="stylesheet" type="text/css" />
}

Ecommerce.WebUI/Views/Admin/AddProduct.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@model Product

<div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                            <li class="breadcrumb-item active">Product Edit</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Add / Edit Product</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <form asp-controller="Admin" asp-action="SaveProduct" enctype="multipart/form-data" method="POST">
                        <input type="hidden" value="@Model.ProductId" name="ProductId">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card-box">

                                    <div class="form-group mb-3">
                                        <label asp-for="Name"></label> <span class="text-danger">*</span>
                                        <input asp-for="Name" class="form-control" placeholder="Product Name">
                                    </div>                                    

                                    <div class="form-group mb-3">
                                        <label asp-for="UnitPrice">Price </label> <span class="text-danger">*</span>
                                        <input asp-for="UnitPrice" class="form-control" placeholder="Product Unit Price">
                                    </div>

                                    <div class="form-group mb-3">
                                        <label asp-for="StockAmount">Stock Amount </label> <span class="text-danger">*</span>
                                        <input asp-for="StockAmount" class="form-control" placeholder="Product Stock Amount">
                                    </div>

                                    <div class="form-group mb-3">
                                        <label asp-for="CategoryId">Category </label> <span class="text-danger">*</span>
                                        <select class="form-control" name="CategoryId" id="CategoryId">
                                            @foreach (Category category in ViewBag.Categories)
                                            {
                                                @if(Model.Category == category){
                                                    <option value="@category.CategoryId" selected>@category.Name</option>
                                                }
                                                else{
                                                    
                                                    <option value="@category.CategoryId">@category.Name</option>
                                                }
                                            }
                                        </select>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            @if(Model.ImageUrl != null){  
                                                <img src="/img/product/@Model.ImageUrl" class="img-fluid" alt="Responsive image">
                                            }
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label asp-for="ImageUrl">Image</label>
                                                <input type="hidden" name="ImageUrl" id="ImageUrl" value="@Model.ImageUrl">
                                                <input type="file" name="imageFile" class="form-control-file" id="ImageUrl">
                                            </div>
                                        </div>
                                    </div>


                                    

                                    
                                </div> <!-- end card-box -->
                            </div> <!-- end col -->


                        </div>
                        <!-- end row -->

                        <div class="row">
                            <div class="col-12">
                                <div class="text-center mb-3">
                                    <button type="submit" class="btn w-sm btn-success waves-effect waves-light">Save</button>
                                </div>
                            </div> <!-- end col -->
                        </div>

                        </form>
                        <!-- end row -->


                        <!-- file preview template -->
                        <div class="d-none" id="uploadPreviewTemplate">
                            <div class="card mt-1 mb-0 shadow-none border">
                                <div class="p-2">
                                    <div class="row align-items-center">
                                        <div class="col-auto">
                                            <img data-dz-thumbnail="" src="#" class="avatar-sm rounded bg-light" alt="">
                                        </div>
                                        <div class="col pl-0">
                                            <a href="javascript:void(0);" class="text-muted font-weight-bold" data-dz-name=""></a>
                                            <p class="mb-0" data-dz-size=""></p>
                                        </div>
                                        <div class="col-auto">
                                            <!-- Button -->
                                            <a href="" class="btn btn-link btn-lg text-muted" data-dz-remove="">
                                                <i class="dripicons-cross"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        
                    </div> <!-- container -->

                </div>


@section Scripts{

        <!-- Summernote js -->
        <script src="/assets/libs/summernote/summernote-bs4.min.js"></script>
        <!-- Select2 js-->
        <script src="/assets/libs/select2/js/select2.min.js"></script>
        <!-- Dropzone file uploads-->
        <script src="/assets/libs/dropzone/min/dropzone.min.js"></script>

        <!-- Init js-->
        <script src="/assets/js/pages/form-fileuploads.init.js"></script>

        <!-- Init js -->
        <script src="/assets/js/pages/add-product.init.js"></script>

}

@section Styles{
        <link href="/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/summernote/summernote-bs4.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/dropzone/min/dropzone.min.css" rel="stylesheet" type="text/css" />
}

Ecommerce.WebUI/Views/Admin/EditCategory.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@model Category

<div class="content">
    <div class="container-fluid">
        <div class="row mt-2">
            <div class="col-md-12">
                <form asp-controller="Admin" asp-action="SaveCategory">
                    <input type="hidden" name="CategoryId" value="@Model.CategoryId">
                     <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control">
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

Ecommerce.WebUI/Views/Admin/EditProduct.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@model Product

<div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">
                        
                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <div class="page-title-right">
                                        <ol class="breadcrumb m-0">
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                                            <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                                            <li class="breadcrumb-item active">Product Edit</li>
                                        </ol>
                                    </div>
                                    <h4 class="page-title">Add / Edit Product</h4>
                                </div>
                            </div>
                        </div>     
                        <!-- end page title --> 

                        <form asp-controller="Admin" asp-action="SaveProduct" enctype="multipart/form-data">
                        <input type="hidden" value="@Model.ProductId" name="ProductId">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card-box">

                                    <div class="form-group mb-3">
                                        <label asp-for="Name"></label> <span class="text-danger">*</span>
                                        <input asp-for="Name" class="form-control" placeholder="Product Name">
                                    </div>                                    

                                    <div class="form-group mb-3">
                                        <label asp-for="UnitPrice">Price </label> <span class="text-danger">*</span>
                                        <input asp-for="UnitPrice" class="form-control" placeholder="Product Unit Price">
                                    </div>

                                    <div class="form-group mb-3">
                                        <label asp-for="StockAmount">Stock Amount </label> <span class="text-danger">*</span>
                                        <input asp-for="StockAmount" class="form-control" placeholder="Product Stock Amount">
                                    </div>

                                    <div class="form-group mb-3">
                                        <label asp-for="CategoryId">Category </label> <span class="text-danger">*</span>
                                        <select class="form-control" name="CategoryId" id="CategoryId">
                                            @foreach (Category category in ViewBag.Categories)
                                            {
                                                @if(Model.Category == category){
                                                    <option value="@category.CategoryId" selected>@category.Name</option>
                                                }
                                                else{
                                                    
                                                    <option value="@category.CategoryId">@category.Name</option>
                                                }
                                            }
                                        </select>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            @if(Model.ImageUrl != null){  
                                                <img src="/img/product/@Model.ImageUrl" class="img-fluid" alt="Responsive image">
                                            }
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label asp-for="ImageUrl">Image</label>
                                                <input type="hidden" name="ImageUrl" id="ImageUrl" value="@Model.ImageUrl">
                                                <input type="file" name="imageFile" class="form-control-file" id="ImageUrl">
                                            </div>
                                        </div>
                                    </div>


                                    

                                    
                                </div> <!-- end card-box -->
                            </div> <!-- end col -->


                        </div>
                        <!-- end row -->

                        <div class="row">
                            <div class="col-12">
                                <div class="text-center mb-3">
                                    <button type="submit" class="btn w-sm btn-success waves-effect waves-light">Save</button>
                                </div>
                            </div> <!-- end col -->
                        </div>

                        </form>
                        <!-- end row -->


                        <!-- file preview template -->
                        <div class="d-none" id="uploadPreviewTemplate">
                            <div class="card mt-1 mb-0 shadow-none border">
                                <div class="p-2">
                                    <div class="row align-items-center">
                                        <div class="col-auto">
                                            <img data-dz-thumbnail="" src="#" class="avatar-sm rounded bg-light" alt="">
                                        </div>
                                        <div class="col pl-0">
                                            <a href="javascript:void(0);" class="text-muted font-weight-bold" data-dz-name=""></a>
                                            <p class="mb-0" data-dz-size=""></p>
                                        </div>
                                        <div class="col-auto">
                                            <!-- Button -->
                                            <a href="" class="btn btn-link btn-lg text-muted" data-dz-remove="">
                                                <i class="dripicons-cross"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        
                    </div> <!-- container -->

                </div>


@section Scripts{

        <!-- Summernote js -->
        <script src="/assets/libs/summernote/summernote-bs4.min.js"></script>
        <!-- Select2 js-->
        <script src="/assets/libs/select2/js/select2.min.js"></script>
        <!-- Dropzone file uploads-->
        <script src="/assets/libs/dropzone/min/dropzone.min.js"></script>

        <!-- Init js-->
        <script src="/assets/js/pages/form-fileuploads.init.js"></script>

        <!-- Init js -->
        <script src="/assets/js/pages/add-product.init.js"></script>

}

@section Styles{
        <link href="/assets/libs/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/summernote/summernote-bs4.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/libs/dropzone/min/dropzone.min.css" rel="stylesheet" type="text/css" />
}

Ecommerce.WebUI/Views/Admin/Index.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

Ecommerce.WebUI/Views/Admin/ListCategory.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@section Styles{
<!-- third party css -->
<link href="/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet"
    type="text/css" />
<!-- third party css end -->
}

@section Scripts{
<!-- third party js -->
<script src="/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<script src="/assets/libs/jquery-datatables-checkboxes/js/dataTables.checkboxes.min.js"></script>
}

@model List<Category>


<div class="content">

    <!-- Start Content-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 my-2">
                <a class="btn btn-success" asp-controller="Admin" asp-action="AddCategory">Add Category</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>

                        @foreach(Category category in Model){
                            <tr>
                                <th scope="row">@category.CategoryId</th>
                                <td>@category.Name</td>
                                <td>
                                    <a asp-controller="Admin" asp-action="DeleteCategory" asp-route-id="@category.CategoryId" class="btn btn-danger">Delete</a>
                                    <a asp-controller="Admin" asp-action="EditCategory" asp-route-id="@category.CategoryId" class="btn btn-warning">Update</a>
                                </td>
                            </tr>
                        }

                    </tbody>
                  </table>
            </div>
        </div>
        
    </div> <!-- container -->

</div>

Ecommerce.WebUI/Views/Admin/ListOrder.cshtml
@section menu{
    @await Html.PartialAsync("_admin_menu")
}

@section user_information{
    @await Component.InvokeAsync("AdminDetail")
}

@model List<Order>


<div class="content">

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                            <li class="breadcrumb-item"><a href="javascript: void(0);">eCommerce</a></li>
                            <li class="breadcrumb-item active">Orders</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Orders</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        

                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        
                                        <th>Order ID</th>
                                        <th>Products</th>
                                        <th>Date</th>
                                        <th>Total</th>
                                        <th>Order Status</th>
                                        <th style="width: 125px;">Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach(Order order in Model){
                                        <tr>
                                            
                                            <td><a href="ecommerce-order-detail.html"
                                                    class="text-body font-weight-bold">@order.OrderId</a> </td>
                                            <td>
                                                @foreach (CartItem cartItem in order.Cart.CartItems)
                                                {
                                                    <a href="#"><img
                                                        src="/img/product/@cartItem.Product.ImageUrl" alt="product-img"
                                                        height="32" /></a>
                                                }
                                                
                                            </td>
                                            <td>
                                                @order.Date
                                            </td>
                                            
                                            <td>
                                                @order.Cart.CalculateTotalPrice()
                                            </td>
                                            
                                            <td>
                                                <h5><span class="badge badge-info">Shipped</span></h5>
                                            </td>
                                            <td>
                                                <a asp-controller="Admin" asp-action="OrderDetail" asp-route-id="@order.OrderId" class="action-icon"> <i
                                                        class="mdi mdi-eye"></i></a>
                                                
                                                <a asp-controller="Admin" asp-action="DeleteOrder" asp-route-id="@order.OrderId" class="action-icon"> <i
                                                        class="mdi mdi-delete"></i></a>
                                            </td>
                                        </tr>
                                    }

                                    


                                </tbody>
                            </table>
                        </div>

                        
                    </div> <!-- end card-body-->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->

Ecommerce.WebUI/Views/Admin/Login.cshtml
@{
    Layout = "_Login_Layout";
}

@model User



<div class="col-md-8 col-lg-6 col-xl-5">
    <div class="card bg-pattern">

        <div class="card-body p-4">

            <div class="text-center w-75 m-auto">
                <p class="text-muted mb-4 mt-3">Enter your username and password to access admin panel.</p>
            </div>

            @if(ViewBag.ErrorMessage != null){
                <div class="text-center w-75 m-auto">
                    <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
                </div>
            }

            <form asp-controller="Admin" asp-action="Login" method="POST">

                <div class="form-group mb-3">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" placeholder="Enter your username" class="form-control">

                </div>

                <div class="form-group mb-3">
                    <label for="password">Password</label>
                    <div class="input-group input-group-merge">
                        <input asp-for="Password" type="password" class="form-control" placeholder="Enter your password">
                        <div class="input-group-append show-password" data-password="true">
                            <div class="input-group-text">
                                <span class="password-eye"></span>
                            </div>
                        </div>
                    </div>
                </div>



               

                <div class="form-group mb-0 text-center">
                    <button class="btn btn-primary btn-block" type="submit"> Log In </button>
                </div>

            </form>

        

        </div> <!-- end card-body -->
    </div>
    <!-- end card -->


    <!-- end row -->

</div> <!-- end col -->